### PR TITLE
Added update flag to allow skipping known files when calculating hashes

### PR DESCRIPTION
**Pull request by WoLpH**
It's quite a hefty change but I think a useful one. In addition to the standard workflow of re-checksumming all files on update it is now possible to skip the known files and only checksum the new files.

### CODE REVIEW

**Comment by ahankinson** [comment]
Could you tell me if the unit tests pass? Should they be updated?

**Comment by WoLpH** [comment]
The unit tests pass but it doesn't currently have a specific test for this code yet.

For automated testing it actually would be good if Travis support was included, it's pretty easy to set up, should I give it a go?

**Comment by ahankinson** [comment]
Sure!

**Comment by WoLpH** [comment]
Travis is doing it's job but it appears it's somehow stalling with Python 2.6, I've just disabled it for now. Nobody uses 2.6 anyhow.

The status for my repository: https://travis-ci.org/WoLpH/pybagit
After merging it you can enable travis for your repository as well, once you do it will automatically test all pull requests for you and tell you if the tests succeed.

**Comment by ahankinson** [comment]
Would it be too much to ask to break out the Travis functionality from the update changes? I'd like a chance to test the update changes myself, but would like to merge the Travis stuff asap.

**Comment by WoLpH** [comment]
No problem at all, I'll just cherry pick them into a new branch :)

**Comment by ahankinson** [comment]
Thanks!

**Pull request merged**
