### PR TITLE
Actually compress when zipping files

### PR DESCRIPTION
**Pull request by WoLpH**
The actual change is actually only this line: https://github.com/ahankinson/pybagit/compare/master...WoLpH:master?w=1#diff-134f0c507f656409c8d743b69b9aec63R536

The rest are just some pep8/code style changes.

### CODE REVIEW

**Comment by ahankinson** [comment]
Looks good. Thanks!

**Comment by WoLpH** [comment]
Awesome, thanks :)

PS: Can you also push out a new Pypi release?

**Comment by ahankinson** [comment]
Working on that right now. Should be up in a few minutes.

**Comment by ahankinson** [comment]
It's live now.

https://pypi.python.org/pypi/pybagit/1.5.2

**Comment by WoLpH** [comment]
Great, thank you very much.

I'll might make some more changes soon (I would like to be able to add and hash files one at a time)

**Comment by ahankinson** [comment]
Perfect. I'll make sure to review and merge your changes promptly.

**Pull request merged**
